name: Terraform Deploy - 09-ci-cd

on:
  push:
    branches: [ main ]
    paths:
      - "09-ci-cd/**" # Dispara el workflow apenas para modificaciones en el directorio 09-ci-cd
  pull_request:
    branches: [ main ]
    paths:
      - "09-ci-cd/**"

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 09-ci-cd # Define el directorio de trabajo para los comandos de Terraform

    steps:
      # Configura el repositorio para que el workflow pueda acceder al código fuente
      - name: Checkout
        uses: actions/checkout@v5

      # Configura el Terraform para ser utilizado en el workflow
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      # Configura las credenciales de AWS para que Terraform pueda interactuar con los servicios de AWS
      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Inicializar, validar y planificar la infraestructura
      - name: Terraform Init
        id: terraform-init
        run: terraform init

      # Formato de Terraform para verificar que el código esté correctamente formateado
      - name: Terraform Format Check
        id: terraform-format
        run: terraform fmt --check
        continue-on-error: true

      # Validación de Terraform para verificar que la configuración sea válida
      - name: Terraform Validate
        id: terraform-validate
        run: terraform validate

      # Planificación de Terraform para mostrar los cambios que se realizarán en la infraestructura
      - name: Terraform Plan
        id: terraform-plan
        run: terraform plan -out plan.out

      # Aplica los cambios en la infraestructura solo si el evento es un push a la rama main
      - name: Terraform Apply
        id: terraform-apply
        run: terraform apply plan.out
        if: github.event_name == 'push' # Solo aplica los cambios en la rama main, no en pull requests
